# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signuo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SignupWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1200, 675)
        MainWindow.setFixedSize(1200, 675)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/signup_bg.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signup_email = QtWidgets.QLineEdit(self.centralwidget)
        self.signup_email.setGeometry(QtCore.QRect(374, 211, 450, 60))
        self.signup_email.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #062b98;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.signup_email.setObjectName("signup_email")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(374, 545, 211, 16))
        self.label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.label.setObjectName("label")
        self.signup_apply = QtWidgets.QPushButton(self.centralwidget)
        self.signup_apply.setGeometry(QtCore.QRect(674, 530, 150, 45))
        self.signup_apply.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #062b98;\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #071d54;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #071d54;\n"
"}\n"
"")
        self.signup_apply.setObjectName("signup_apply")
        self.first_name = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name.setEnabled(True)
        self.first_name.setGeometry(QtCore.QRect(374, 122, 190, 60))
        self.first_name.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.first_name.setObjectName("first_name")
        self.login_switch = QtWidgets.QPushButton(self.centralwidget)
        self.login_switch.setGeometry(QtCore.QRect(540, 530, 150, 45))
        self.login_switch.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"text-decoration: underline;\n"
"    }")
        self.login_switch.setObjectName("login_switch")
        self.last_name = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name.setEnabled(True)
        self.last_name.setGeometry(QtCore.QRect(635, 122, 190, 60))
        self.last_name.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.last_name.setObjectName("last_name")
        self.signup_password = QtWidgets.QLineEdit(self.centralwidget)
        self.signup_password.setGeometry(QtCore.QRect(374, 300, 450, 60))
        self.signup_password.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.signup_password.setObjectName("signup_password")
        self.confirm_signup_password = QtWidgets.QLineEdit(self.centralwidget)
        self.confirm_signup_password.setGeometry(QtCore.QRect(374, 389, 450, 60))
        self.signup_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_signup_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_signup_password.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.confirm_signup_password.setObjectName("confirm_signup_password")
        self.studen_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.studen_radio.setGeometry(QtCore.QRect(430, 470, 95, 20))
        self.studen_radio.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}\n"
"")
        self.studen_radio.setObjectName("studen_radio")
        self.admin_radio = QtWidgets.QRadioButton(self.centralwidget)
        self.admin_radio.setGeometry(QtCore.QRect(430, 505, 95, 20))
        self.admin_radio.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}\n"
"")
        self.admin_radio.setObjectName("admin_radio")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(374, 470, 51, 16))
        self.label_2.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signup_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.label.setText(_translate("MainWindow", "Already have an account?"))
        self.signup_apply.setText(_translate("MainWindow", "Signup"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "First name"))
        self.login_switch.setText(_translate("MainWindow", "Login"))
        self.last_name.setPlaceholderText(_translate("MainWindow", "Last name"))
        self.signup_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.confirm_signup_password.setPlaceholderText(_translate("MainWindow", "Confirm password"))
        self.studen_radio.setText(_translate("MainWindow", "Student"))
        self.admin_radio.setText(_translate("MainWindow", "Admin"))
        self.label_2.setText(_translate("MainWindow", "Role:"))


