# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Controller


class Ui_StudentHomeWindow(object):
    def setViewBorrowBG(self,MainWindow):
        
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/student_browse.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")
        
    def setProfileBG(self, MainWindow):
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/student_details.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")

    def setBorrowBG(self, MainWindow):
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/student_borrow.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")
    def setBrowseBG(self, MainWindow):
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/student_plain.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.resize(1200, 675)
        MainWindow.setFixedSize(1200, 675)
        MainWindow.setStyleSheet("QMainWindow{\n"
"background-image: url(\"assets/student_plain.png\");\n"
"background-position: top left;\n"
"background-repeat: no-repeat;\n"
"background-size: cover;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.view_borrow_widget = QtWidgets.QWidget(self.centralwidget)
        self.view_borrow_widget.setGeometry(QtCore.QRect(0, 120, 1201, 521))
        self.view_borrow_widget.setObjectName("view_borrow_widget")
        # self.tableWidget = QtWidgets.QTableWidget(self.view_borrow_widget)
        # self.tableWidget.setGeometry(QtCore.QRect(90, 120, 1021, 381))
        # self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(5)
        # self.tableWidget.setRowCount(0)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(2, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(3, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.tableWidget.setHorizontalHeaderItem(4, item)
        ######################################
        self.borrowTreeWidget = QtWidgets.QTreeWidget(self.view_borrow_widget)
        self.borrowTreeWidget.setGeometry(QtCore.QRect(90, 150, 1021, 381))
        self.borrowTreeWidget.setStyleSheet("")
        self.borrowTreeWidget.setObjectName("borrowTreeWidget")
        self.view_borrow = QtWidgets.QPushButton(self.centralwidget)
        self.view_borrow.setGeometry(QtCore.QRect(388, 63, 196, 47))
        self.view_borrow.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"text-decoration: underline;\n"
"    }")
        self.view_borrow.setText("")
        self.view_borrow.setObjectName("view_borrow")
        self.edit_profile = QtWidgets.QPushButton(self.centralwidget)
        self.edit_profile.setGeometry(QtCore.QRect(604, 68, 138, 39))
        self.edit_profile.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"text-decoration: underline;\n"
"    }")
        self.edit_profile.setText("")
        self.edit_profile.setObjectName("edit_profile")
        self.browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.browse_button.setGeometry(QtCore.QRect(751, 68, 138, 39))
        self.browse_button.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"text-decoration: underline;\n"
"    }")
        self.browse_button.setText("")
        self.browse_button.setObjectName("browse_button")
        self.borrow_button = QtWidgets.QPushButton(self.centralwidget)
        self.borrow_button.setGeometry(QtCore.QRect(881, 63, 196, 47))
        self.borrow_button.setStyleSheet("QPushButton {\n"
"        background-color: transparent;\n"
"        border: none;\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"text-decoration: underline;\n"
"    }")
        self.borrow_button.setText("")
        self.borrow_button.setObjectName("borrow_button")
        self.browse_widget = QtWidgets.QWidget(self.centralwidget)
        self.browse_widget.setGeometry(QtCore.QRect(0, 120, 1201, 521))
        self.browse_widget.setObjectName("browse_widget")
        self.search_input = QtWidgets.QLineEdit(self.browse_widget)
        self.search_input.setEnabled(True)
        self.search_input.setGeometry(QtCore.QRect(333, 66, 530, 60))
        self.search_input.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.search_input.setPlaceholderText("")
        self.search_input.setObjectName("search_input")
        self.search_apply = QtWidgets.QPushButton(self.browse_widget)
        self.search_apply.setGeometry(QtCore.QRect(759, 66, 108, 60))
        self.search_apply.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #062b98;\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #071d54;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #071d54;\n"
"}\n"
"")
        self.search_apply.setObjectName("search_apply")
        self.radio_by_isbn = QtWidgets.QRadioButton(self.browse_widget)
        self.radio_by_isbn.setGeometry(QtCore.QRect(360, 140, 95, 20))
        self.radio_by_isbn.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}")
        self.radio_by_isbn.setObjectName("radio_by_isbn")
        self.radio_by_name = QtWidgets.QRadioButton(self.browse_widget)
        self.radio_by_name.setGeometry(QtCore.QRect(460, 140, 95, 20))
        self.radio_by_name.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}")
        self.radio_by_name.setObjectName("radio_by_name")
        self.radio_by_author = QtWidgets.QRadioButton(self.browse_widget)
        self.radio_by_author.setGeometry(QtCore.QRect(550, 140, 95, 20))
        self.radio_by_author.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}")
        self.radio_by_author.setObjectName("radio_by_author")
        self.radio_by_year = QtWidgets.QRadioButton(self.browse_widget)
        self.radio_by_year.setGeometry(QtCore.QRect(650, 140, 95, 20))
        self.radio_by_year.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}")
        self.radio_by_year.setObjectName("radio_by_year")
        self.radio_by_category = QtWidgets.QRadioButton(self.browse_widget)
        self.radio_by_category.setGeometry(QtCore.QRect(740, 140, 121, 20))
        self.radio_by_category.setStyleSheet("QRadioButton {\n"
"    color: #f7f9fe;\n"
"    color: #062b98;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"\n"
"}")
        self.radio_by_category.setObjectName("radio_by_category")
        self.treeWidget = QtWidgets.QTreeWidget(self.browse_widget)
        self.treeWidget.setGeometry(QtCore.QRect(90, 170, 1021, 331))
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setObjectName("treeWidget")
        self.borrow_widget = QtWidgets.QWidget(self.centralwidget)
        self.borrow_widget.setGeometry(QtCore.QRect(0, 120, 1201, 621))
        self.borrow_widget.setObjectName("borrow_widget")
        self.isbn_input_2 = QtWidgets.QLineEdit(self.borrow_widget)
        self.isbn_input_2.setEnabled(True)
        self.isbn_input_2.setGeometry(QtCore.QRect(100, 60, 430, 60))
        self.isbn_input_2.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.isbn_input_2.setPlaceholderText("")
        self.isbn_input_2.setObjectName("isbn_input_2")
        self.find_book_apply = QtWidgets.QPushButton(self.borrow_widget)
        self.find_book_apply.setGeometry(QtCore.QRect(550, 60, 171, 60))
        self.find_book_apply.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #062b98;\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #071d54;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #071d54;\n"
"}\n"
"")
        self.find_book_apply.setObjectName("find_book_apply")
        self.book_details_widget = QtWidgets.QWidget(self.borrow_widget)
        self.book_details_widget.setGeometry(QtCore.QRect(0, 130, 1201, 451))
        self.book_details_widget.setObjectName("book_details_widget")
        self.book_name_label = QtWidgets.QLabel(self.book_details_widget)
        self.book_name_label.setGeometry(QtCore.QRect(334, 15, 311, 16))
        self.book_name_label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.book_name_label.setObjectName("book_name_label")
        self.author_label = QtWidgets.QLabel(self.book_details_widget)
        self.author_label.setGeometry(QtCore.QRect(334, 69, 291, 16))
        self.author_label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.author_label.setObjectName("author_label")
        self.year_label = QtWidgets.QLabel(self.book_details_widget)
        self.year_label.setGeometry(QtCore.QRect(334, 129, 361, 16))
        self.year_label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.year_label.setObjectName("year_label")
        self.category_label = QtWidgets.QLabel(self.book_details_widget)
        self.category_label.setGeometry(QtCore.QRect(334, 188, 531, 21))
        self.category_label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.category_label.setObjectName("category_label")
        self.copies_label = QtWidgets.QLabel(self.book_details_widget)
        self.copies_label.setGeometry(QtCore.QRect(334, 245, 55, 21))
        self.copies_label.setStyleSheet("QLabel {\n"
"\n"
"        color: #062b98;\n"
"            font-size: 18px;\n"
"            font-family: Arial, sans-serif;\n"
"\n"
"    }")
        self.copies_label.setObjectName("copies_label")
        self.borrow_apply = QtWidgets.QPushButton(self.book_details_widget)
        self.borrow_apply.setGeometry(QtCore.QRect(220, 290, 171, 60))
        self.borrow_apply.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #062b98;\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #071d54;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #071d54;\n"
"}\n"
"")
        self.borrow_apply.setObjectName("borrow_apply")
        self.book_details_widget.raise_()
        self.isbn_input_2.raise_()
        self.find_book_apply.raise_()
        self.edit_profile_widget = QtWidgets.QWidget(self.centralwidget)
        self.edit_profile_widget.setGeometry(QtCore.QRect(0, 120, 1201, 551))
        self.edit_profile_widget.setObjectName("edit_profile_widget")
        self.email_edit_input = QtWidgets.QLineEdit(self.edit_profile_widget)
        self.email_edit_input.setGeometry(QtCore.QRect(100, 164, 429, 60))
        self.email_edit_input.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.email_edit_input.setPlaceholderText("")
        self.email_edit_input.setObjectName("email_edit_input")
        self.first_name = QtWidgets.QLineEdit(self.edit_profile_widget)
        self.first_name.setEnabled(True)
        self.first_name.setGeometry(QtCore.QRect(100, 63, 195, 60))
        self.first_name.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.first_name.setPlaceholderText("")
        self.first_name.setObjectName("first_name")
        self.confirm_password_edit_input = QtWidgets.QLineEdit(self.edit_profile_widget)
        self.confirm_password_edit_input.setGeometry(QtCore.QRect(100, 364, 429, 60))
        self.confirm_password_edit_input.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.confirm_password_edit_input.setPlaceholderText("")
        self.confirm_password_edit_input.setObjectName("confirm_password_edit_input")
        self.last_name = QtWidgets.QLineEdit(self.edit_profile_widget)
        self.last_name.setEnabled(True)
        self.last_name.setGeometry(QtCore.QRect(334, 63, 195, 60))
        self.last_name.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.last_name.setPlaceholderText("")
        self.last_name.setObjectName("last_name")
        self.password_edit_input = QtWidgets.QLineEdit(self.edit_profile_widget)
        self.password_edit_input.setGeometry(QtCore.QRect(100, 265, 429, 60))
        self.password_edit_input.setStyleSheet("QLineEdit {\n"
"    border: 1.5px solid #062b98;\n"
"    border-radius: 20;\n"
"    padding: 20px;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font: 16px Arial, sans-serif;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #0743d8;\n"
"}\n"
"")
        self.password_edit_input.setPlaceholderText("")
        self.password_edit_input.setObjectName("password_edit_input")
        self.edit_student_button = QtWidgets.QPushButton(self.edit_profile_widget)
        self.edit_student_button.setGeometry(QtCore.QRect(100, 449, 430, 58))
        self.edit_student_button.setStyleSheet("QPushButton{\n"
"    border-radius: 15px;\n"
"    background-color: #062b98;\n"
"    color: #f7f9fe;\n"
"    font-size: 16px;\n"
"    font-family: Arial, sans-serif;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #071d54;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #071d54;\n"
"}\n"
"")
        self.edit_student_button.setObjectName("edit_student_button")
        self.year_number = QtWidgets.QSpinBox(self.edit_profile_widget)
        self.year_number.setGeometry(QtCore.QRect(568, 73, 71, 41))
        self.year_number.setStyleSheet("QSpinBox {\n"
"    color: #f7f9fe;\n"
"    background-color: #062b98;\n"
"    border: 1px solid #062b98;\n"
"    border-radius: 5px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow::disabled,\n"
"QSpinBox::down-arrow::disabled {\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.year_number.setMinimum(1)
        self.year_number.setMaximum(7)
        self.year_number.setObjectName("year_number")
        self.edit_profile_widget.raise_()
        self.borrow_widget.raise_()
        self.browse_widget.raise_()
        self.view_borrow_widget.raise_()
        self.view_borrow.raise_()
        self.edit_profile.raise_()
        self.browse_button.raise_()
        self.borrow_button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.view_borrow_widget.hide()
        self.borrow_widget.hide()
        # self.browse_widget.hide()
        self.edit_profile_widget.hide()

        self.retranslateUi(MainWindow)
        
        self.edit_profile.clicked.connect(lambda: self.setProfileBG(MainWindow)) # type: ignore
        self.view_borrow.clicked.connect(lambda: self.setViewBorrowBG(MainWindow)) # type: ignore
        self.borrow_button.clicked.connect(lambda: self.setBorrowBG(MainWindow)) # type: ignore
        self.browse_button.clicked.connect(lambda: self.setBrowseBG(MainWindow)) # type: ignore
        # self.find_book_apply.clicked.connect(self.borrow_widget.show)
        
        
        
        
        self.view_borrow.clicked.connect(self.view_borrow_widget.show) # type: ignore
        self.view_borrow.clicked.connect(self.borrow_widget.hide) # type: ignore
        self.view_borrow.clicked.connect(self.browse_widget.hide) # type: ignore
        self.edit_profile.clicked.connect(self.view_borrow_widget.hide) # type: ignore
        self.edit_profile.clicked.connect(self.borrow_widget.hide) # type: ignore
        self.edit_profile.clicked.connect(self.browse_widget.hide) # type: ignore
        self.browse_button.clicked.connect(self.browse_widget.show) # type: ignore
        self.browse_button.clicked.connect(self.view_borrow_widget.hide) # type: ignore
        self.browse_button.clicked.connect(self.borrow_widget.hide) # type: ignore
        self.borrow_button.clicked.connect(self.borrow_widget.show) # type: ignore
        self.borrow_button.clicked.connect(self.view_borrow_widget.hide) # type: ignore
        self.borrow_button.clicked.connect(self.browse_widget.hide) # type: ignore
        self.edit_profile.clicked.connect(self.edit_profile_widget.show) # type: ignore
        self.view_borrow.clicked.connect(self.edit_profile_widget.hide) # type: ignore
        self.browse_button.clicked.connect(self.edit_profile_widget.hide) # type: ignore
        self.borrow_button.clicked.connect(self.edit_profile_widget.hide) # type: ignore
       # self.find_book_apply.clicked.connect(self.book_details_widget.show) # type: ignore
        self.borrow_button.clicked.connect(self.book_details_widget.hide) # type: ignore
        self.browse_button.clicked.connect(self.book_details_widget.hide) # type: ignore
        self.edit_profile.clicked.connect(self.book_details_widget.hide) # type: ignore
        self.view_borrow.clicked.connect(self.book_details_widget.hide) # type: ignore
        self.borrow_apply.clicked.connect(self.book_details_widget.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.search_apply.clicked.connect(self.search) # type: ignore
        self.browse_button.clicked.connect(self.get_all_books) # type: ignore
        self.find_book_apply.clicked.connect(self.get_book_to_borrow) # type: ignore
        self.borrow_apply.clicked.connect(self.borrow_book) # type: ignore
        self.view_borrow.clicked.connect(self.view_borrowed_books) # type: ignore
        self.edit_profile.clicked.connect(self.get_student_data) # type: ignore
        self.edit_student_button.clicked.connect(self.update_student) # type: ignore

        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # item = self.tableWidget.horizontalHeaderItem(0)
        # item.setText(_translate("MainWindow", "ISBN"))
        # item = self.tableWidget.horizontalHeaderItem(1)
        # item.setText(_translate("MainWindow", "Name"))
        # item = self.tableWidget.horizontalHeaderItem(2)
        # item.setText(_translate("MainWindow", "Category"))
        # item = self.tableWidget.horizontalHeaderItem(3)
        # item.setText(_translate("MainWindow", "Start Date"))
        # item = self.tableWidget.horizontalHeaderItem(4)
        # item.setText(_translate("MainWindow", "End Date"))
        self.borrowTreeWidget.headerItem().setText(0, _translate("MainWindow", "ISBN"))
        self.borrowTreeWidget.headerItem().setText(1, _translate("MainWindow", "Name"))
        self.borrowTreeWidget.headerItem().setText(2, _translate("MainWindow", "Category"))
        self.borrowTreeWidget.headerItem().setText(3, _translate("MainWindow", "Start Date"))
        self.borrowTreeWidget.headerItem().setText(4, _translate("MainWindow", "End Date"))
       
        #############################
        self.search_apply.setText(_translate("MainWindow", "Search"))
        self.radio_by_isbn.setText(_translate("MainWindow", "By isbn"))
        self.radio_by_name.setText(_translate("MainWindow", "By name"))
        self.radio_by_author.setText(_translate("MainWindow", "By author"))
        self.radio_by_year.setText(_translate("MainWindow", "By year"))
        self.radio_by_category.setText(_translate("MainWindow", "By category"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "ISBN"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Author"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Year"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Category"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "Available Copies"))
        self.find_book_apply.setText(_translate("MainWindow", "Find Book"))
        self.book_name_label.setText(_translate("MainWindow", "book"))
        self.author_label.setText(_translate("MainWindow", "author"))
        self.year_label.setText(_translate("MainWindow", "year"))
        self.category_label.setText(_translate("MainWindow", "category"))
        self.copies_label.setText(_translate("MainWindow", "copies"))
        self.borrow_apply.setText(_translate("MainWindow", "Borrow"))
        self.edit_student_button.setText(_translate("MainWindow", "Update Personal Details"))
        self.get_all_books()

    def get_all_books(self):
        books = Controller.get_all_books()
        self.treeWidget.clear()
        for book in books:
                item = QtWidgets.QTreeWidgetItem(self.treeWidget)
                item.setText(0, book.title)
                item.setText(1, str(book.ISBN))
                item.setText(2, book.author)
                item.setText(3, str(book.year))
                item.setText(4, book.categoryName)
                available_copies,total_copies,borrowed_copies = Controller.count_available_copies(book.id)
                item.setText(5, str(available_copies))
              

    def search(self):
        books = []
        if not self.search_input.text():
                return self.get_all_books()
        if self.radio_by_isbn.isChecked():
            books = Controller.search_book_by_isbn(self.search_input.text().lower())
        elif self.radio_by_name.isChecked():
            books = Controller.search_book_by_title(self.search_input.text().lower())
        elif self.radio_by_author.isChecked():
            books = Controller.search_book_by_author(self.search_input.text().lower())
        elif self.radio_by_year.isChecked():
            books = Controller.search_book_by_publication_year(self.search_input.text().lower())
        elif self.radio_by_category.isChecked():
            books = Controller.search_by_category(self.search_input.text().lower())
        else:
            return self.get_all_books()
        self.treeWidget.clear()
        for book in books:
            item = QtWidgets.QTreeWidgetItem(self.treeWidget)
            item.setText(0, book.title)
            item.setText(1, str(book.ISBN))
            item.setText(2, book.author)
            item.setText(3, str(book.year))
            item.setText(4, book.categoryName)
            available_copies,total_copies,borrowed_copies = Controller.count_available_copies(book.id)
            item.setText(5, str(available_copies))

    num_of_copies=0
    book_id_edit = 0
    def get_book_to_borrow(self):
        isbn = self.isbn_input_2.text().lower()

        if not isbn:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "Please enter ISBN")
            return
        book,self.book_id_edit = Controller.get_book_to_edit(isbn)
        self.num_of_copies,x,y = Controller.count_available_copies(self.book_id_edit)
        if not book:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "Book not found")
            return
        self.book_name_label.setText(book.title)
        self.author_label.setText(book.author)
        self.year_label.setText(str(book.year))
        # self.isbn_label.setText(str(book.ISBN))
        self.category_label.setText(book.categoryName)
        self.copies_label.setText(str(self.num_of_copies))
        self.book_details_widget.show()

    def borrow_book(self):
        isbn = self.isbn_input_2.text().lower()
        if self.num_of_copies == 0:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "No available copies")
            return
        if Controller.validate_borrow(isbn) == False:
            QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "You already borrowed this book")
            return
        Controller.borrow_book(self.book_id_edit, isbn)
        self.get_all_books()
        
        QtWidgets.QMessageBox.information(self.centralwidget, "Success", "Book borrowed successfully")

    def view_borrowed_books(self):
        borrowed_books = Controller.get_borrowed_books()
        self.borrowTreeWidget.clear()
        for book in borrowed_books:
                item = QtWidgets.QTreeWidgetItem(self.borrowTreeWidget)
                item.setText(0, str(book.ISBN))
                item.setText(1, book.bookName)
                item.setText(2, book.categoryName)
                item.setText(3, str(book.startDate.date().strftime("%Y-%m-%d")))
                item.setText(4, str(book.endDate.date().strftime("%Y-%m-%d")))

    def get_student_data(self):
        self.first_name.setText(Controller.logged_in_user.firstname)
        self.last_name.setText(Controller.logged_in_user.lastname)
        self.email_edit_input.setText(Controller.logged_in_user.email)
        self.year_number.setValue(Controller.logged_in_user.year)
        
    def update_student(self):
        if(self.first_name.text()!=""):
                Controller.logged_in_user.firstname=self.first_name.text()
        if(self.last_name.text()!=""):
                Controller.logged_in_user.lastname=self.last_name.text()
        if(self.email_edit_input.text()!=""):
                Controller.logged_in_user.email=self.email_edit_input.text()

        Controller.logged_in_user.year=self.year_number.value()
                

        if(self.password_edit_input.text()!=""):
            if(self.password_edit_input.text()==self.confirm_password_edit_input.text()):
                Controller.logged_in_user.password=self.password_edit_input.text()
            else:
                QtWidgets.QMessageBox.warning(self.centralwidget, "Error", "Passwords don't match")
                return
        
        
        Controller.update_user(Controller.logged_in_user)
        QtWidgets.QMessageBox.information(self.centralwidget, "Success", "Profile updated successfully")
        self.password_edit_input.setText("")
        self.confirm_password_edit_input.setText("")
        
           


